language: python

sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

python:
  - "3.6"

git:
  depth: 1

before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver

install:
  - pip3 install -r requirements.txt

env:
  - TRAVIS_SECURE_ENV_VARS=true

before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - cp .env.example .env
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic

script:
  - coverage run --source='.' manage.py test --noinput khubkhaoapp/tests --verbosity 2
  - coverage report
