language: python

python:
  - "3.6"

git:
  depth: 1

install:
  - pip3 install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test khubkhaoapp/tests/
